services:
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=your_database_name
      - INFLUXDB_ORG=Home
    volumes:
      - ./influxdb/data:/var/lib/influxdb2:rw
      - ./influxdb/config/config.yaml:/etc/influxdb2/config.yaml:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    user: ${USER_UID}:1000
    environment:
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
    ports:
      - ${GRAFANA_UI_PORT}:3000
    volumes:
      - ./grafana/config:/etc/grafana/provisioning/datasources:ro
      - ./grafana/data:/var/lib/grafana:rw
    depends_on:
      - influxdb
    restart: unless-stopped

  mqtt-broker:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/config/passwd:/mosquitto/config/passwd:rw
    restart: unless-stopped

  telegraf:
    image: telegraf:latest
    environment:
      - INFLUXDB_HOST=${INFLUXDB_HOST}
      - INFLUXDB_PORT=${INFLUXDB_PORT}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - mqtt-broker
    restart: unless-stopped

  mqtt-explorer:
    image: smeagolworms4/mqtt-explorer
    user: "1000:1000"
    ports:
      - ${MQTT_EXPLORER_UI_PORT}:4000
    volumes:
      - ./mqtt-explorer/config:/mqtt-explorer/config:rw
    depends_on:
      - mqtt-broker
    restart: unless-stopped

  trigger:
    build: python-apps
    command: python trigger.py
    env_file:
      - .env
    volumes:
      - ./python-apps/src:/app:ro
    restart: unless-stopped
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "trigger.logs"
    depends_on:
      - fluentd

  pseudo-mqtt-sensor:
    build: python-apps
    command: python pseudo-sensor.py
    env_file:
      - .env
    volumes:
      - ./python-apps/src:/app:ro
    restart: unless-stopped
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "trigger.logs"
    depends_on:
      - fluentd

  fluentd:
    build: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/config:/fluentd/etc:ro

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    user: root
    volumes:
      - ./prometheus/config/config.yaml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/data:/prometheus:rw
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - ${PROMETHEUS_UI_PORT}:9090
