version: '3'

services:
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=your_database_name
      - INFLUXDB_ORG=Home
    volumes:
      - ./influxdb/data:/var/lib/influxdb2:rw
      - ./influxdb/config/config.yaml:/etc/influxdb2/config.yaml:ro

  grafana:
    image: grafana/grafana
    user: "1000:1000"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana:rw
    depends_on:
      - influxdb

  mqtt-broker:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/config/passwd:/mosquitto/config/passwd:rw

  mqtt-explorer:
    image: smeagolworms4/mqtt-explorer
    user: "1000:1000"
    ports:
      - 4000:4000
    volumes:
      - ./mqtt-explorer/config:/mqtt-explorer/config:rw

  trigger:
    build: python-apps
    command: python trigger.py
    volumes:
      - ./python-apps/src:/app:ro
