apiVersion: 1

deleteDatasources:
  - name: "InfluxDB_v2_InfluxQL"
    orgId: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      # This database should be mapped to a bucket
      dbName: Test Measurements
      httpMode: GET
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Token ${INFLUXDB_TOKEN}'